name: kongkerongdian
on:
  workflow_dispatch:

  schedule:
    - cron: '53 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kongkerongdian
        env:
          ppkv61023: ${{ secrets.ppkv61023 }}
        run: |
          printf '%s' "$ppkv61023" | jq -r .rfz17 | /bin/bash
          printf '%s' "$tqw78683" | jq -r .b52 | /bin/bash
          printf '%s' "$aw9" | jq -r .jonwx300 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nEsm9P98
          path: "*.zip"
          retention-days: 1
